// Package trainingplan stores AI-generated training plans — structured weekly
// or multi-week training proposals that materialise the output of an AI
// analysis of the user's past training sessions. Each plan stores the AI's
// reasoning, the generation parameters (prompt, model), and the concrete
// planned sessions per day.
package trainingplan

import (
	"context"
	"database/sql"
	"fmt"
	"time"
)

// GenerationParams captures how the plan was generated by the AI.
type GenerationParams struct {
	Prompt   string `json:"prompt,omitempty"`
	System   string `json:"system,omitempty"`
	Model    string `json:"model,omitempty"`
	Provider string `json:"provider,omitempty"`
}

// TrainingPlan is the top-level container for an AI-generated training plan.
// It holds metadata, the AI's reasoning, and a collection of sessions.
type TrainingPlan struct {
	ID               string            `json:"id"`
	Title            string            `json:"title"`
	Description      string            `json:"description,omitempty"`
	Reasoning        string            `json:"reasoning,omitempty"`
	GenerationParams GenerationParams  `json:"generationParams"`
	WeekCount        int               `json:"weekCount"`
	StartDate        string            `json:"startDate,omitempty"` // YYYY-MM-DD
	EndDate          string            `json:"endDate,omitempty"`   // YYYY-MM-DD
	Status           string            `json:"status"`             // "draft" | "active" | "archived"
	SessionCount     int               `json:"sessionCount"`
	CreatedAt        string            `json:"createdAt"`
	UpdatedAt        string            `json:"updatedAt,omitempty"`
}

const (
	PlanStatusDraft    = "draft"
	PlanStatusActive   = "active"
	PlanStatusArchived = "archived"
)

// TrainingPlanSession is one concrete session within a training plan.
type TrainingPlanSession struct {
	ID                   string  `json:"id"`
	PlanID               string  `json:"planId"`
	WeekNumber           int     `json:"weekNumber"`           // 1-based week within plan
	DayOfWeek            int     `json:"dayOfWeek"`            // 0=Monday .. 6=Sunday
	Date                 string  `json:"date,omitempty"`       // YYYY-MM-DD (optional, computed from plan start)
	TrainingType         string  `json:"trainingType,omitempty"`
	Title                string  `json:"title,omitempty"`
	Description          string  `json:"description,omitempty"`
	TargetDistanceMeters float64 `json:"targetDistanceMeters,omitempty"`
	TargetDurationSecs   float64 `json:"targetDurationSeconds,omitempty"`
	TargetPaceSecPerKm   float64 `json:"targetPaceSecondsPerKm,omitempty"`
	TargetHeartRateMin   float64 `json:"targetHeartRateMin,omitempty"`
	TargetHeartRateMax   float64 `json:"targetHeartRateMax,omitempty"`
	Intensity            string  `json:"intensity,omitempty"`   // "easy" | "moderate" | "hard" | "recovery"
	SortOrder            int     `json:"sortOrder"`
	Notes                string  `json:"notes,omitempty"`
}

func EnsureTables(ctx context.Context, db *sql.DB) error {
	statements := []string{
		`CREATE TABLE IF NOT EXISTS training_plans (
			id TEXT PRIMARY KEY,
			title TEXT NOT NULL,
			description TEXT,
			reasoning TEXT,
			generation_prompt TEXT,
			generation_system TEXT,
			generation_model TEXT,
			generation_provider TEXT,
			week_count INTEGER NOT NULL DEFAULT 1,
			start_date TEXT,
			end_date TEXT,
			status TEXT NOT NULL DEFAULT 'draft',
			session_count INTEGER NOT NULL DEFAULT 0,
			created_at TEXT NOT NULL,
			updated_at TEXT
		);`,
		`CREATE TABLE IF NOT EXISTS training_plan_sessions (
			id TEXT PRIMARY KEY,
			plan_id TEXT NOT NULL,
			week_number INTEGER NOT NULL,
			day_of_week INTEGER NOT NULL,
			date TEXT,
			training_type TEXT,
			title TEXT,
			description TEXT,
			target_distance_meters REAL,
			target_duration_seconds REAL,
			target_pace_sec_per_km REAL,
			target_heart_rate_min REAL,
			target_heart_rate_max REAL,
			intensity TEXT,
			sort_order INTEGER NOT NULL DEFAULT 0,
			notes TEXT,
			FOREIGN KEY (plan_id) REFERENCES training_plans(id) ON DELETE CASCADE
		);`,
		`CREATE INDEX IF NOT EXISTS idx_tps_plan_id ON training_plan_sessions(plan_id);`,
		`CREATE INDEX IF NOT EXISTS idx_tp_status ON training_plans(status);`,
	}
	for _, stmt := range statements {
		if _, err := db.ExecContext(ctx, stmt); err != nil {
			return fmt.Errorf("ensure training plan tables: %w", err)
		}
	}
	return nil
}

// --- TrainingPlan CRUD ---

func InsertPlan(ctx context.Context, db *sql.DB, plan TrainingPlan, sessions []TrainingPlanSession) error {
	if db == nil {
		return fmt.Errorf("database not available")
	}
	if plan.CreatedAt == "" {
		plan.CreatedAt = time.Now().UTC().Format(time.RFC3339)
	}
	plan.SessionCount = len(sessions)
	plan.UpdatedAt = plan.CreatedAt

	tx, err := db.BeginTx(ctx, nil)
	if err != nil {
		return fmt.Errorf("begin training plan tx: %w", err)
	}
	defer func() { _ = tx.Rollback() }()

	_, err = tx.ExecContext(ctx,
		`INSERT INTO training_plans (id, title, description, reasoning, generation_prompt, generation_system, generation_model, generation_provider, week_count, start_date, end_date, status, session_count, created_at, updated_at)
		VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)`,
		plan.ID, plan.Title, plan.Description, plan.Reasoning,
		plan.GenerationParams.Prompt, plan.GenerationParams.System,
		plan.GenerationParams.Model, plan.GenerationParams.Provider,
		plan.WeekCount, plan.StartDate, plan.EndDate,
		plan.Status, plan.SessionCount, plan.CreatedAt, plan.UpdatedAt,
	)
	if err != nil {
		return fmt.Errorf("insert training plan: %w", err)
	}

	for _, s := range sessions {
		s.PlanID = plan.ID
		if s.ID == "" {
			s.ID = fmt.Sprintf("tps-%d-%d", time.Now().UnixNano(), s.SortOrder)
		}
		_, err := tx.ExecContext(ctx,
			`INSERT INTO training_plan_sessions (id, plan_id, week_number, day_of_week, date, training_type, title, description, target_distance_meters, target_duration_seconds, target_pace_sec_per_km, target_heart_rate_min, target_heart_rate_max, intensity, sort_order, notes)
			VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)`,
			s.ID, s.PlanID, s.WeekNumber, s.DayOfWeek, s.Date,
			s.TrainingType, s.Title, s.Description,
			s.TargetDistanceMeters, s.TargetDurationSecs, s.TargetPaceSecPerKm,
			s.TargetHeartRateMin, s.TargetHeartRateMax,
			s.Intensity, s.SortOrder, s.Notes,
		)
		if err != nil {
			return fmt.Errorf("insert training plan session: %w", err)
		}
	}

	if err := tx.Commit(); err != nil {
		return fmt.Errorf("commit training plan: %w", err)
	}
	return nil
}

func ListPlans(ctx context.Context, db *sql.DB, statusFilter string) ([]TrainingPlan, error) {
	if db == nil {
		return []TrainingPlan{}, nil
	}

	if statusFilter != "" {
		rows, err := db.QueryContext(ctx,
			`SELECT id, title, COALESCE(description, ''), COALESCE(reasoning, ''), COALESCE(generation_prompt, ''), COALESCE(generation_system, ''), COALESCE(generation_model, ''), COALESCE(generation_provider, ''), week_count, COALESCE(start_date, ''), COALESCE(end_date, ''), status, session_count, created_at, COALESCE(updated_at, '') FROM training_plans WHERE status = ? ORDER BY created_at DESC`,
			statusFilter,
		)
		if err != nil {
			return nil, fmt.Errorf("list training plans: %w", err)
		}
		defer rows.Close()

		plans := make([]TrainingPlan, 0)
		for rows.Next() {
			var p TrainingPlan
			if err := rows.Scan(&p.ID, &p.Title, &p.Description, &p.Reasoning,
				&p.GenerationParams.Prompt, &p.GenerationParams.System,
				&p.GenerationParams.Model, &p.GenerationParams.Provider,
				&p.WeekCount, &p.StartDate, &p.EndDate,
				&p.Status, &p.SessionCount, &p.CreatedAt, &p.UpdatedAt); err != nil {
				return nil, fmt.Errorf("scan training plan: %w", err)
			}
			plans = append(plans, p)
		}
		return plans, rows.Err()
	}

	rows, err := db.QueryContext(ctx,
		`SELECT id, title, COALESCE(description, ''), COALESCE(reasoning, ''), COALESCE(generation_prompt, ''), COALESCE(generation_system, ''), COALESCE(generation_model, ''), COALESCE(generation_provider, ''), week_count, COALESCE(start_date, ''), COALESCE(end_date, ''), status, session_count, created_at, COALESCE(updated_at, '') FROM training_plans ORDER BY created_at DESC`,
	)
	if err != nil {
		return nil, fmt.Errorf("list training plans: %w", err)
	}
	defer rows.Close()

	plans := make([]TrainingPlan, 0)
	for rows.Next() {
		var p TrainingPlan
		if err := rows.Scan(&p.ID, &p.Title, &p.Description, &p.Reasoning,
			&p.GenerationParams.Prompt, &p.GenerationParams.System,
			&p.GenerationParams.Model, &p.GenerationParams.Provider,
			&p.WeekCount, &p.StartDate, &p.EndDate,
			&p.Status, &p.SessionCount, &p.CreatedAt, &p.UpdatedAt); err != nil {
			return nil, fmt.Errorf("scan training plan: %w", err)
		}
		plans = append(plans, p)
	}
	return plans, rows.Err()
}

func GetPlan(ctx context.Context, db *sql.DB, id string) (TrainingPlan, []TrainingPlanSession, error) {
	if db == nil {
		return TrainingPlan{}, []TrainingPlanSession{}, fmt.Errorf("database not available")
	}

	var p TrainingPlan
	err := db.QueryRowContext(ctx,
		`SELECT id, title, COALESCE(description, ''), COALESCE(reasoning, ''), COALESCE(generation_prompt, ''), COALESCE(generation_system, ''), COALESCE(generation_model, ''), COALESCE(generation_provider, ''), week_count, COALESCE(start_date, ''), COALESCE(end_date, ''), status, session_count, created_at, COALESCE(updated_at, '') FROM training_plans WHERE id = ?`, id,
	).Scan(&p.ID, &p.Title, &p.Description, &p.Reasoning,
		&p.GenerationParams.Prompt, &p.GenerationParams.System,
		&p.GenerationParams.Model, &p.GenerationParams.Provider,
		&p.WeekCount, &p.StartDate, &p.EndDate,
		&p.Status, &p.SessionCount, &p.CreatedAt, &p.UpdatedAt)
	if err != nil {
		return TrainingPlan{}, []TrainingPlanSession{}, fmt.Errorf("get training plan %s: %w", id, err)
	}

	sessions, err := ListPlanSessions(ctx, db, id)
	if err != nil {
		return p, []TrainingPlanSession{}, err
	}
	return p, sessions, nil
}

func UpdatePlanStatus(ctx context.Context, db *sql.DB, id, status string) error {
	if db == nil {
		return fmt.Errorf("database not available")
	}
	updatedAt := time.Now().UTC().Format(time.RFC3339)
	res, err := db.ExecContext(ctx,
		`UPDATE training_plans SET status = ?, updated_at = ? WHERE id = ?`,
		status, updatedAt, id,
	)
	if err != nil {
		return fmt.Errorf("update training plan status: %w", err)
	}
	rows, _ := res.RowsAffected()
	if rows == 0 {
		return fmt.Errorf("training plan not found: %s", id)
	}
	return nil
}

func DeletePlan(ctx context.Context, db *sql.DB, id string) error {
	if db == nil {
		return fmt.Errorf("database not available")
	}
	res, err := db.ExecContext(ctx, `DELETE FROM training_plans WHERE id = ?`, id)
	if err != nil {
		return fmt.Errorf("delete training plan: %w", err)
	}
	rows, _ := res.RowsAffected()
	if rows == 0 {
		return fmt.Errorf("training plan not found: %s", id)
	}
	return nil
}

// --- TrainingPlanSession queries ---

func ListPlanSessions(ctx context.Context, db *sql.DB, planID string) ([]TrainingPlanSession, error) {
	if db == nil {
		return []TrainingPlanSession{}, nil
	}
	rows, err := db.QueryContext(ctx,
		`SELECT id, plan_id, week_number, day_of_week, COALESCE(date, ''), COALESCE(training_type, ''), COALESCE(title, ''), COALESCE(description, ''), COALESCE(target_distance_meters, 0), COALESCE(target_duration_seconds, 0), COALESCE(target_pace_sec_per_km, 0), COALESCE(target_heart_rate_min, 0), COALESCE(target_heart_rate_max, 0), COALESCE(intensity, ''), sort_order, COALESCE(notes, '')
		FROM training_plan_sessions WHERE plan_id = ? ORDER BY week_number ASC, day_of_week ASC, sort_order ASC`,
		planID,
	)
	if err != nil {
		return nil, fmt.Errorf("list plan sessions: %w", err)
	}
	defer rows.Close()

	sessions := make([]TrainingPlanSession, 0)
	for rows.Next() {
		var s TrainingPlanSession
		if err := rows.Scan(&s.ID, &s.PlanID, &s.WeekNumber, &s.DayOfWeek,
			&s.Date, &s.TrainingType, &s.Title, &s.Description,
			&s.TargetDistanceMeters, &s.TargetDurationSecs, &s.TargetPaceSecPerKm,
			&s.TargetHeartRateMin, &s.TargetHeartRateMax,
			&s.Intensity, &s.SortOrder, &s.Notes); err != nil {
			return nil, fmt.Errorf("scan plan session: %w", err)
		}
		sessions = append(sessions, s)
	}
	return sessions, rows.Err()
}